/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.Funcionario;
import servicos.FuncionarioServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Vinicius
 */
public class UICadFuncionario extends javax.swing.JInternalFrame  {

    /**
     * Creates new form UICadFuncionario
     */
    public UICadFuncionario() {
        initComponents();
        jtNome.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCargo = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jrRecep = new javax.swing.JRadioButton();
        jrGere = new javax.swing.JRadioButton();
        jrSuper = new javax.swing.JRadioButton();
        jrCam = new javax.swing.JRadioButton();
        jrSecre = new javax.swing.JRadioButton();
        jrCont = new javax.swing.JRadioButton();
        jrCoo = new javax.swing.JRadioButton();
        jrTel = new javax.swing.JRadioButton();
        jtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCPFFocusGained(evt);
            }
        });
        jtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCPFKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Sexo:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSalarioFocusLost(evt);
            }
        });
        jtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSalarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Salário:");

        bgSexo.add(jrMasculino);
        jrMasculino.setSelected(true);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        bgCargo.add(jrRecep);
        jrRecep.setText("Recepcionista");
        jrRecep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrRecepKeyPressed(evt);
            }
        });

        bgCargo.add(jrGere);
        jrGere.setText("Gerente");
        jrGere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrGereKeyPressed(evt);
            }
        });

        bgCargo.add(jrSuper);
        jrSuper.setText("Supervisor");
        jrSuper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSuperKeyPressed(evt);
            }
        });

        bgCargo.add(jrCam);
        jrCam.setText("Camareiro");
        jrCam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCamKeyPressed(evt);
            }
        });

        bgCargo.add(jrSecre);
        jrSecre.setText("Secretária");
        jrSecre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSecreKeyPressed(evt);
            }
        });

        bgCargo.add(jrCont);
        jrCont.setText("Controler");
        jrCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrContKeyPressed(evt);
            }
        });

        bgCargo.add(jrCoo);
        jrCoo.setText("Cooder. de sistemas");
        jrCoo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCooKeyPressed(evt);
            }
        });

        bgCargo.add(jrTel);
        jrTel.setText("Telefonista");
        jrTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrTelKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jrRecep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrGere, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrSuper, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrCam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrSecre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrCont, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrCoo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrTel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jrGere)
                        .addGap(60, 60, 60)
                        .addComponent(jrSecre))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jrRecep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrCam)))
                .addGap(43, 43, 43)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrSuper)
                    .addComponent(jrCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrCoo)
                    .addComponent(jrTel))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrGere)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrSuper)
                        .addComponent(jrSecre)
                        .addComponent(jrCoo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrRecep)
                    .addComponent(jrCam)
                    .addComponent(jrCont)
                    .addComponent(jrTel)))
        );

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Senha:");

        jtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSenhaFocusLost(evt);
            }
        });
        jtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSenhaKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .addComponent(jtCPF)
                            .addComponent(jtNome)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jrMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jrFeminino))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jtSalario))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrMasculino)
                    .addComponent(jrFeminino))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtCPF, jtNome, jtSalario, jtSenha, jtTelefone});

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulo.png"))); // NOI18N

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbLimpar.setBackground(new java.awt.Color(255, 255, 255));
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jLayeredPane3.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLayeredPane3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCadastrar, jbLimpar});

        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCadastrar, jbLimpar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3)
                    .addComponent(jLayeredPane2))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastrarFun(){
        try {                 
            Funcionario f = new Funcionario();
            if(!util.validacao.validarString(jtNome.getText())){
                throw new NumberFormatException("Nome invalido!");
            }
            
            if(jtSenha.getText().isEmpty()){
                throw new NumberFormatException("Senha invalida!");
            }
            if(!util.validacao.validarNumero(jtTelefone.getText())){
                throw new NumberFormatException("Telefone invalida!");
            }
            if(!util.validacao.validarCPF(jtCPF.getText())){
                throw new NumberFormatException("CPF invalido!");
            }
            if(!util.validacao.validarSalario(jtSalario.getText())){
                throw new NumberFormatException("Salário invalido!");
            }
            f.setNome(jtNome.getText());
            f.setSenha(jtSenha.getPassword().toString());
            f.setTelefone(jtTelefone.getText());
            f.setCpf(jtCPF.getText());
            f.setSalario(Double.parseDouble(jtSalario.getText()));

            if(jrMasculino.isSelected()){
                f.setSexo(jrMasculino.getText());
            }else if(jrFeminino.isSelected()){
                f.setSexo(jrFeminino.getText());
            }else{
                throw new NumberFormatException("Selecione o Sexo!");
            }

            if(jrGere.isSelected()){
                f.setCargo(jrGere.getText());
            }else if(jrRecep.isSelected()){
                f.setCargo(jrRecep.getText());
            }else if(jrSecre.isSelected()){
                f.setCargo(jrSecre.getText());
            }else if(jrCam.isSelected()){
                f.setCargo(jrCam.getText());
            }else if(jrSuper.isSelected()){
                f.setCargo(jrSuper.getText());
            }else if(jrCont.isSelected()){
                f.setCargo(jrCont.getText());
            }else if(jrCoo.isSelected()){
                f.setCargo(jrCoo.getText());
            }else if(jrGere.isSelected()){
                f.setCargo(jrGere.getText());
            }else{
                throw new NumberFormatException("Selecione o Cargo!");
            }

             FuncionarioServicos FS = ServicosFactory.getFuncionarioServicos();
                FS.cadastrarFuncinario(f);

                JOptionPane.showMessageDialog(
                        rootPane, 
                        "Funcionario cadastrado com sucesso!");
                limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void limpar(){
        jtNome.setText(null);
        jtSenha.setText(null);
        jtTelefone.setText(null);
        jtCPF.setText(null);
        jtSalario.setText(null);
        bgSexo.clearSelection();
        bgCargo.clearSelection();
    }
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrarFun();
        
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
       if(jtNome.getText().isEmpty()){            
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtNome.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSenha.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCPF.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCPFKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrGere.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtCPFKeyPressed

    private void jrGereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrGereKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSecre.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrGereKeyPressed

    private void jrSecreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSecreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSuper.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSecreKeyPressed

    private void jrCooKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCooKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrRecep.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCooKeyPressed

    private void jrRecepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrRecepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCam.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrRecepKeyPressed

    private void jrCamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCamKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCont.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCamKeyPressed

    private void jrContKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrContKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrTel.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrContKeyPressed

    private void jrTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrTelKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrMasculino.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrTelKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrFeminino.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSalario.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jtSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSalarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarFun();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jtSalarioKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarFun();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        if(jtTelefone.getText().isEmpty()){            
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtTelefone.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            
        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCPFFocusGained
        if(jtCPF.getText().isEmpty()){            
            jtCPF.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtCPF.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            
        }
    }//GEN-LAST:event_jtCPFFocusGained

    private void jtSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSalarioFocusLost
        if(jtSalario.getText().isEmpty()){            
            jtSalario.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtSalario.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            
        }
    }//GEN-LAST:event_jtSalarioFocusLost

    private void jrSuperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSuperKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCoo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSuperKeyPressed

    private void jtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtTelefone.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtSenhaKeyPressed

    private void jtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSenhaFocusLost
        if(jtSenha.getText().isEmpty()){            
            jtSenha.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtSenha.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            
        }
    }//GEN-LAST:event_jtSenhaFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCargo;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JRadioButton jrCam;
    private javax.swing.JRadioButton jrCont;
    private javax.swing.JRadioButton jrCoo;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrGere;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JRadioButton jrRecep;
    private javax.swing.JRadioButton jrSecre;
    private javax.swing.JRadioButton jrSuper;
    private javax.swing.JRadioButton jrTel;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSalario;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
