/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.Quarto;
import modelo.Reserva;
import servicos.QuartoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author QI
 */
public class UICadQuarto extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadQuarto
     */
    public UICadQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        bgStatus = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNum = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jtAndar = new javax.swing.JTextField();
        jtNumCom = new javax.swing.JTextField();
        jrLuxo = new javax.swing.JRadioButton();
        jrCobertura = new javax.swing.JRadioButton();
        jrCasal = new javax.swing.JRadioButton();
        jrSolteiro = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Número:");

        jLabel2.setText("Valor:");

        jLabel3.setText("Tipo");

        jLabel4.setText("Andar:");

        jLabel6.setText("N°  Cômodos:");

        jtNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumFocusLost(evt);
            }
        });
        jtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumKeyPressed(evt);
            }
        });

        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });
        jtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorKeyPressed(evt);
            }
        });

        jtAndar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAndarFocusLost(evt);
            }
        });
        jtAndar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAndarKeyPressed(evt);
            }
        });

        jtNumCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumComFocusLost(evt);
            }
        });
        jtNumCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumComKeyPressed(evt);
            }
        });

        bgTipo.add(jrLuxo);
        jrLuxo.setText("Luxo");
        jrLuxo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrLuxoKeyPressed(evt);
            }
        });

        bgTipo.add(jrCobertura);
        jrCobertura.setText("Cobertura");
        jrCobertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCoberturaKeyPressed(evt);
            }
        });

        bgTipo.add(jrCasal);
        jrCasal.setText("Casal");
        jrCasal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCasalKeyPressed(evt);
            }
        });

        bgTipo.add(jrSolteiro);
        jrSolteiro.setText("Solteiro");
        jrSolteiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSolteiroKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtAndar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNumCom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrLuxo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrCobertura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrCasal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrSolteiro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtNumCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jrLuxo)
                                .addGap(42, 42, 42)
                                .addComponent(jrCobertura)
                                .addGap(38, 38, 38)
                                .addComponent(jrCasal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrSolteiro))
                            .addComponent(jtAndar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtAndar, jtNum, jtNumCom, jtValor});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrLuxo)
                    .addComponent(jrCobertura)
                    .addComponent(jrCasal)
                    .addComponent(jrSolteiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtAndar, jtNum, jtNumCom, jtValor});

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCadastrar, jbLimpar});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCadastrar, jbLimpar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastrar(){
         try {                 
             Quarto f = new Quarto();
             
            if(!util.validacao.validarNumero(jtNum.getText())){
                throw new NumberFormatException("Número invalido!");
            }
            if(!util.validacao.validarNumero(jtValor.getText())){
                throw new NumberFormatException("Valor invalido!");
            }
            if(!util.validacao.validarNumero(jtAndar.getText())){
                throw new NumberFormatException("Andar invalido!");
            }
            if(!util.validacao.validarNumero(jtNumCom.getText())){
                throw new NumberFormatException("Número de comodos invalido!");
            }
            f.setNum(Integer.parseInt(jtNum.getText()));
            
            f.setNumComodos(Integer.parseInt(jtNumCom.getText()));
            f.setAndar(jtAndar.getText());
            f.setValor(Double.parseDouble(jtValor.getText()));

            
            f.setStatus("Vago");
            

            if(jrLuxo.isSelected()){
                f.setTipo(jrLuxo.getText());
            }else if(jrCobertura.isSelected()){
                f.setTipo(jrCobertura.getText());
            }else if(jrCasal.isSelected()){
                f.setTipo(jrCasal.getText());
            }else if(jrSolteiro.isSelected()){
                f.setTipo(jrSolteiro.getText());
            }else{
                throw new NumberFormatException("Selecione o Tipo!");
            }

             QuartoServicos FS = ServicosFactory.getQuartoServicos();
                FS.cadastrarQuarto(f);
                 
                
            
                

                JOptionPane.showMessageDialog(
                        rootPane, 
                        "Quarto cadastrado com sucesso!");
                limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limpar(){
        jtNum.setText(null);
        jtValor.setText(null);
        jtAndar.setText(null);
        jtNumCom.setText(null);
        bgStatus.clearSelection();
        bgTipo.clearSelection();
    }
            
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtValor.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNumKeyPressed

    private void jtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrLuxo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtValorKeyPressed

    private void jrLuxoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrLuxoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCobertura.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrLuxoKeyPressed

    private void jrCoberturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCoberturaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCasal.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCoberturaKeyPressed

    private void jrCasalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCasalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSolteiro.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCasalKeyPressed

    private void jrSolteiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSolteiroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtAndar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSolteiroKeyPressed

    private void jtAndarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAndarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtNumCom.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAndarKeyPressed

    private void jtNumComKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumComKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jtNumComKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jtNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumFocusLost
        if(jtNum.getText().isEmpty()){            
            jtNum.setBorder(BorderFactory.createLineBorder(Color.RED));

        }else{
           jtNum.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtNumFocusLost

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
        if(jtValor.getText().isEmpty()){            
            jtValor.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtValor.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtValorFocusLost

    private void jtAndarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAndarFocusLost
        if(jtAndar.getText().isEmpty()){            
            jtAndar.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtAndar.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtAndarFocusLost

    private void jtNumComFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumComFocusLost
        if(jtNumCom.getText().isEmpty()){            
            jtNumCom.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtNumCom.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtNumComFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JRadioButton jrCasal;
    private javax.swing.JRadioButton jrCobertura;
    private javax.swing.JRadioButton jrLuxo;
    private javax.swing.JRadioButton jrSolteiro;
    private javax.swing.JTextField jtAndar;
    private javax.swing.JTextField jtNum;
    private javax.swing.JTextField jtNumCom;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
