/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Quarto;
import servicos.QuartoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Vinicius
 */
public class UIManQuarto extends javax.swing.JInternalFrame {
    DefaultTableModel dtm = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"Código","N° Quarto","Valor","Tipo","Andar","Status","N° Cômodos"});
    /**
     * Creates new form UIManQuarto
     */
    public UIManQuarto() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgStatus = new javax.swing.ButtonGroup();
        bgTipo = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jtPesq = new javax.swing.JTextField();
        jComboPesq = new javax.swing.JComboBox<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuarto = new javax.swing.JTable();
        jbDeletar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtIdQuarto = new javax.swing.JTextField();
        jtNum = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jtNumComo = new javax.swing.JTextField();
        jtAndar = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jrSolteiro = new javax.swing.JRadioButton();
        jrCasal = new javax.swing.JRadioButton();
        jrCobertura = new javax.swing.JRadioButton();
        jrLuxo = new javax.swing.JRadioButton();
        jbAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Pesquisa");

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jComboPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "N° Quarto", "Valor", "Andar", "Status", "N° Cômodos" }));
        jComboPesq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboPesqItemStateChanged(evt);
            }
        });
        jComboPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboPesqKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jComboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Número Quarto", "Valor", "Tipo", "Andar", "Status", "N° Cômodos"
            }
        ));
        jTableQuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuartoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuarto);

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });
        jbDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDeletarKeyPressed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/detalhes.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jbBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbBuscarKeyPressed(evt);
            }
        });

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });
        jbAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAtualizarKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Código");

        jLabel3.setText("N° Quarto");

        jLabel4.setText("Valor");

        jLabel6.setText("Andar");

        jLabel8.setText("N° Cômodos");

        jtIdQuarto.setEditable(false);

        jtNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumFocusLost(evt);
            }
        });
        jtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumKeyPressed(evt);
            }
        });

        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });
        jtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorKeyPressed(evt);
            }
        });

        jtNumComo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumComoFocusLost(evt);
            }
        });
        jtNumComo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumComoKeyPressed(evt);
            }
        });

        jtAndar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAndarFocusLost(evt);
            }
        });
        jtAndar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAndarKeyPressed(evt);
            }
        });

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        bgTipo.add(jrSolteiro);
        jrSolteiro.setText("Solteiro");
        jrSolteiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSolteiroKeyPressed(evt);
            }
        });

        bgTipo.add(jrCasal);
        jrCasal.setText("Casal");
        jrCasal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCasalKeyPressed(evt);
            }
        });

        bgTipo.add(jrCobertura);
        jrCobertura.setText("Cobertura");
        jrCobertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCoberturaKeyPressed(evt);
            }
        });

        bgTipo.add(jrLuxo);
        jrLuxo.setText("Luxo");
        jrLuxo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrLuxoKeyPressed(evt);
            }
        });

        jLayeredPane4.setLayer(jrSolteiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrCasal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrCobertura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrLuxo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrCobertura)
                    .addComponent(jrLuxo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrSolteiro)
                    .addComponent(jrCasal))
                .addGap(15, 15, 15))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrLuxo)
                    .addComponent(jrCasal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrCobertura)
                    .addComponent(jrSolteiro))
                .addContainerGap())
        );

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtIdQuarto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtNumComo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtAndar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtAndar)
                            .addComponent(jtNum)
                            .addComponent(jtIdQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jtValor)
                            .addComponent(jtNumComo))))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtAndar, jtIdQuarto, jtNum, jtValor});

        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtNumComo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtAndar, jtIdQuarto, jtNum, jtNumComo, jtValor});

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manquarto.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLayeredPane1)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherTabela(){
        try {
             QuartoServicos FS = ServicosFactory.getQuartoServicos();
             ArrayList<Quarto> func = FS.buscarQuarto();
             
             for(int i=0; i<func.size(); i++){
                dtm.addRow(new String[]{
                    String.valueOf(func.get(i).getIdQuarto()),
                    String.valueOf(func.get(i).getNum()),
                    String.valueOf(func.get(i).getValor()),
                    
                    func.get(i).getTipo(),
                    func.get(i).getAndar(),
                    func.get(i).getStatus(),
                    
                    String.valueOf(func.get(i).getNumComodos())});
                
             }//fecha for
             jTableQuarto.setModel(dtm);
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"Erro!"+e.getMessage());
         }//fecha catch
     }//fecha preenchertabela
    
    
     private void limpar(){
         dtm.setNumRows(0);
     }//fecha limpar
     
     
     private void deletar(){
         try {
             int linha = jTableQuarto.getSelectedRow();
             if(linha ==-1){
                 JOptionPane.showMessageDialog(rootPane, "Selecione uma linha ");
             }else{
                 String id = jTableQuarto.getValueAt(linha, 0).toString();
                 int op = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja excluir??","Alerta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE );
                 if(op==0){
                     QuartoServicos ws = ServicosFactory.getQuartoServicos();
                     ws.deletar(Long.parseLong(id));
                             
                 }
             
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Erro "+e.getMessage());
         }
     }
     private void filtrar(){
         try {
             if(jtPesq.getText().isEmpty()){
                 limpar();
                 preencherTabela();
             }else{
                 String query = "";
                 String filtro = jComboPesq.getSelectedItem().toString();
                 if(filtro.equalsIgnoreCase("Código")){
                     query = "where idquarto like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("N° Quarto")){
                     query = "where num like '%"+jtPesq.getText()+"%'";
                 
                 }else if(filtro.equalsIgnoreCase("Valor")){
                     query = "where valor like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("tipo")){
                     query = "where tipo like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("andar")){
                     query = "where andar like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("status")){
                     query = "where status like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("N° Cômodos")){
                     query = "where numcomodos like '"+jtPesq.getText()+"%'";
                 }
                 QuartoServicos ps = ServicosFactory.getQuartoServicos();
                 ArrayList<Quarto> fun = ps.filtrar(query);
                 
                 for(int i = 0; i< fun.size();i++){
                    dtm.addRow(new String[]{
                        String.valueOf(fun.get(i).getIdQuarto()),
                        String.valueOf(fun.get(i).getNum()),
                        String.valueOf(fun.get(i).getValor()),
                        fun.get(i).getTipo(),
                        fun.get(i).getAndar(),
                        fun.get(i).getStatus(),
                                               
                        String.valueOf(fun.get(i).getNumComodos())
                    });
                }
                jTableQuarto.setModel(dtm);
             }
         } catch (Exception e) {
             jtPesq.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage());
         }
     }
     
     private void alterar(){
        
        int linha = jTableQuarto.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
            return;
        }
        jtIdQuarto.setText(jTableQuarto.getValueAt(linha, 0).toString());
        jtNum.setText(jTableQuarto.getValueAt(linha, 1).toString());
        jtValor.setText(jTableQuarto.getValueAt(linha, 2).toString());
        
        if(jTableQuarto.getValueAt(linha, 3).toString().equalsIgnoreCase("luxo")){
            jrLuxo.setSelected(true);
        }else  if(jTableQuarto.getValueAt(linha, 3).toString().equalsIgnoreCase("cobertura")){
            jrCobertura.setSelected(true);
        }else if(jTableQuarto.getValueAt(linha, 3).toString().equalsIgnoreCase("casal")){
            jrCasal.setSelected(true);
        }else{
            jrSolteiro.setSelected(true);
        } 
         
         
        jtAndar.setText(jTableQuarto.getValueAt(linha, 4).toString());   
        
        
        
              
        jtNumComo.setText(jTableQuarto.getValueAt(linha, 6).toString());        
        
        
         
        
               
    }//fecha alterar
     
     private void confirmarAlteracao(){
        try {
            Quarto f = new Quarto();
            
            if(!util.validacao.validarNumero(jtNum.getText())){
                throw new NumberFormatException("Número invalido!");
            }
            if(!util.validacao.validarNumero(jtValor.getText())){
                throw new NumberFormatException("Valor invalido!");
            }
            if(!util.validacao.validarNumero(jtAndar.getText())){
                throw new NumberFormatException("Andar invalido!");
            }
            if(!util.validacao.validarNumero(jtNumComo.getText())){
                throw new NumberFormatException("Número de comodos invalido!");
            }
            f.setIdQuarto(Long.parseLong(jtIdQuarto.getText()));
            
            f.setNum(Integer.parseInt(jtNum.getText()));
            f.setValor(Double.parseDouble(jtValor.getText()));
            
            f.setAndar(jtAndar.getText());
            
            
            
            
            f.setNumComodos(Integer.parseInt(jtNumComo.getText()));
            
            int linha = jTableQuarto.getSelectedRow();
            f.setStatus((String)jTableQuarto.getValueAt(linha, 5));
            
            if(jrLuxo.isSelected()){
                f.setTipo(jrLuxo.getText());
            }else if(jrCobertura.isSelected()){
                f.setTipo(jrCobertura.getText());
            }else if(jrCasal.isSelected()){
                f.setTipo(jrCasal.getText());
            }else{
                f.setTipo(jrSolteiro.getText());
            }
            
            
            //Enviando o objeto pVO para o banco de dados
            QuartoServicos ps = ServicosFactory.getQuartoServicos();
            //Chamando o método 
            ps.alterarQuarto(f);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Quarto alterado com sucesso!");
            
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha confirmarAlteracao
    private void limparCampos(){
        jtNum.setText(null);
        jtValor.setText(null);
        jtIdQuarto.setText(null);
        jtAndar.setText(null);
        jtNumComo.setText(null);
        
        bgTipo.clearSelection();
    }
    
    private void buscarLinhaSelecionada(){
        try {
            /* Buscando a linha que o usuário clicou */
            int linha = jTableQuarto.getSelectedRow();
            
            /* Testando se o usuário selecionou alguma linha. */
            if (linha != -1) {
                
                /* todos os dados da linha selecionada pelo usuário */
                String idquarto = (String) jTableQuarto.getValueAt(linha, 0);
                String num = (String) jTableQuarto.getValueAt(linha, 1);
                String valor = (String) jTableQuarto.getValueAt(linha, 2);
                String tipo = (String) jTableQuarto.getValueAt(linha, 3);
                String andar = (String) jTableQuarto.getValueAt(linha, 4);
                
                String status = (String) jTableQuarto.getValueAt(linha, 5);
                String numComodos = (String) jTableQuarto.getValueAt(linha, 6);
               
               
               
                
                JOptionPane.showMessageDialog(this,
                        "Dados do Quarto selecionado: "
                        +"\ncódigo: "+idquarto
                        +"\nN° Quarto: "+num
                        +"\nValor: "+valor
                        +"\nTipo: "+tipo
                        +"\nAndar: "+andar
                        +"\nStatus: "+status
                        +"\nN° Cômodos: "+numComodos
                        
                );
            } else {
                JOptionPane.showMessageDialog(this,
                        "Você não selecionou nenhuma linha!");
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao selecionar uma linha! " + e.getMessage());
        }//fecha catch
    }//fecha método
    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limpar();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscarLinhaSelecionada();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
        limpar();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        confirmarAlteracao();
        limpar();
        preencherTabela();
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jComboPesqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboPesqItemStateChanged
         limpar();
        filtrar();
    }//GEN-LAST:event_jComboPesqItemStateChanged

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jTableQuartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuartoMouseClicked
        alterar();
    }//GEN-LAST:event_jTableQuartoMouseClicked

    private void jtPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jComboPesq.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtPesqKeyPressed

    private void jComboPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboPesqKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbAtualizar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jComboPesqKeyPressed

    private void jbAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAtualizarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbBuscar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbAtualizarKeyPressed

    private void jbBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbBuscarKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbLimpar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbBuscarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbDeletar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDeletarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtNum.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbDeletarKeyPressed

    private void jtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtValor.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNumKeyPressed

    private void jtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtAndar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtValorKeyPressed

    private void jtAndarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAndarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtNumComo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAndarKeyPressed

    private void jtNumComoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumComoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrLuxo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNumComoKeyPressed

    private void jrLuxoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrLuxoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCasal.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrLuxoKeyPressed

    private void jrCasalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCasalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCobertura.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCasalKeyPressed

    private void jrCoberturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCoberturaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSolteiro.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCoberturaKeyPressed

    private void jrSolteiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSolteiroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            confirmarAlteracao();
            limpar();
            preencherTabela();
            limparCampos();
        }//fecha if
    }//GEN-LAST:event_jrSolteiroKeyPressed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            confirmarAlteracao();
            limpar();
            preencherTabela();
            limparCampos();
        }//fecha if
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jtNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumFocusLost
        if(jtNum.getText().isEmpty()){            
            jtNum.setBorder(BorderFactory.createLineBorder(Color.RED));

        }else{
           jtNum.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtNumFocusLost

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
        if(jtValor.getText().isEmpty()){            
            jtValor.setBorder(BorderFactory.createLineBorder(Color.RED));

        }else{
           jtValor.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtValorFocusLost

    private void jtAndarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAndarFocusLost
        if(jtAndar.getText().isEmpty()){            
            jtAndar.setBorder(BorderFactory.createLineBorder(Color.RED));

        }else{
           jtAndar.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtAndarFocusLost

    private void jtNumComoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumComoFocusLost
        if(jtNumComo.getText().isEmpty()){            
            jtNumComo.setBorder(BorderFactory.createLineBorder(Color.RED));

        }else{
           jtNumComo.setBorder(BorderFactory.createLineBorder(Color.gray));

            
        }
    }//GEN-LAST:event_jtNumComoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JComboBox<String> jComboPesq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQuarto;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JRadioButton jrCasal;
    private javax.swing.JRadioButton jrCobertura;
    private javax.swing.JRadioButton jrLuxo;
    private javax.swing.JRadioButton jrSolteiro;
    private javax.swing.JTextField jtAndar;
    private javax.swing.JTextField jtIdQuarto;
    private javax.swing.JTextField jtNum;
    private javax.swing.JTextField jtNumComo;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
