/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Funcionario;
import servicos.FuncionarioServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Vinicius
 */
public class UIManFuncionario extends javax.swing.JInternalFrame {
    DefaultTableModel dtm = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"Código","Nome","Senha","Telefone","CPF","Cargo","Sexo","Salário"});
    /**
     * Creates new form UIManFuncionario
     */
    public UIManFuncionario() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCargo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jtPesq = new javax.swing.JTextField();
        jcomboPesq = new javax.swing.JComboBox<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTableFunc = new javax.swing.JScrollPane();
        jTableFun = new javax.swing.JTable();
        jbDeletar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jrRecep = new javax.swing.JRadioButton();
        jrGere = new javax.swing.JRadioButton();
        jrSuper = new javax.swing.JRadioButton();
        jrCam = new javax.swing.JRadioButton();
        jrSecre = new javax.swing.JRadioButton();
        jrCont = new javax.swing.JRadioButton();
        jrCoo = new javax.swing.JRadioButton();
        jrTel = new javax.swing.JRadioButton();
        jtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jrCod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manutencao.png"))); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Pesquisa");

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Telefone", "CPF", "Cargo", "Sexo", "Salário" }));
        jcomboPesq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboPesqItemStateChanged(evt);
            }
        });
        jcomboPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboPesqKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcomboPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcomboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcomboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableFun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Senha", "Telefone", "CPF", "Cargo", "Sexo", "Salário"
            }
        ));
        jTableFun.getTableHeader().setReorderingAllowed(false);
        jTableFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFunMouseClicked(evt);
            }
        });
        jTableFunc.setViewportView(jTableFun);

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });
        jbDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDeletarKeyPressed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/detalhes.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jbBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbBuscarKeyPressed(evt);
            }
        });

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });
        jbAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAtualizarKeyPressed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jTableFunc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTableFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAtualizar, jbBuscar, jbDeletar, jbLimpar});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTableFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbAtualizar, jbBuscar, jbDeletar, jbLimpar});

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Nome:");

        jtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCPFFocusGained(evt);
            }
        });
        jtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCPFKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Sexo:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSalarioFocusLost(evt);
            }
        });
        jtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSalarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Salário:");

        jrMasculino.setSelected(true);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jrRecep.setText("Recepcionista");
        jrRecep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrRecepKeyPressed(evt);
            }
        });

        jrGere.setText("Gerente");
        jrGere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrGereKeyPressed(evt);
            }
        });

        jrSuper.setText("Supervisor");
        jrSuper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSuperKeyPressed(evt);
            }
        });

        jrCam.setText("Camareiro");
        jrCam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCamKeyPressed(evt);
            }
        });

        jrSecre.setText("Secretária");
        jrSecre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSecreKeyPressed(evt);
            }
        });

        jrCont.setText("Controler");
        jrCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrContKeyPressed(evt);
            }
        });

        jrCoo.setText("Cooder. de sistemas");
        jrCoo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCooKeyPressed(evt);
            }
        });

        jrTel.setText("Telefonista");
        jrTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrTelKeyPressed(evt);
            }
        });

        jLayeredPane6.setLayer(jrRecep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrGere, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrSuper, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrCam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrSecre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrCont, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrCoo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jrTel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrGere)
                    .addComponent(jrRecep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jrCam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrCont))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jrSecre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrSuper)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrCoo)
                    .addComponent(jrTel))
                .addGap(74, 74, 74))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrGere)
                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrSuper)
                        .addComponent(jrCoo)
                        .addComponent(jrSecre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrRecep)
                    .addComponent(jrCam)
                    .addComponent(jrCont)
                    .addComponent(jrTel)))
        );

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Senha:");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jrCod.setEditable(false);
        jrCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jrCodFocusLost(evt);
            }
        });
        jrCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCodKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Código: ");

        jtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSenhaFocusLost(evt);
            }
        });
        jtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSenhaKeyPressed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLayeredPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrCod, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane4Layout.createSequentialGroup()
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(23, 23, 23)
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jrCod, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jrMasculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrFeminino))
                                    .addComponent(jLabel6)))
                            .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLayeredPane4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jrCod, jtCPF, jtNome, jtSenha, jtTelefone});

        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrCod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jrMasculino)
                            .addComponent(jrFeminino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jrCod, jtCPF, jtNome, jtSalario, jtSenha, jtTelefone});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherTabela(){
        try {
             FuncionarioServicos FS = ServicosFactory.getFuncionarioServicos();
             ArrayList<Funcionario> func = FS.buscarFuncionario();
             
             for(int i=0; i<func.size(); i++){
                dtm.addRow(new String[]{
                    String.valueOf(func.get(i).getIdFuncionario()),
                    func.get(i).getNome(),
                    func.get(i).getSenha(),
                    func.get(i).getTelefone(),
                    func.get(i).getCpf(),
                    func.get(i).getCargo(),
                    func.get(i).getSexo(),
                    String.valueOf(func.get(i).getSalario())});
                
             }//fecha for
             jTableFun.setModel(dtm);
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"Erro!"+e.getMessage());
         }//fecha catch
     }//fecha preenchertabela
    
    
     private void limpar(){
         dtm.setNumRows(0);
     }//fecha limpar
     
     
     private void deletar(){
         try {
             int linha = jTableFun.getSelectedRow();
             if(linha ==-1){
                 JOptionPane.showMessageDialog(rootPane, "Selecione uma linha ");
             }else{
                 String id = jTableFun.getValueAt(linha, 0).toString();
                 int op = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja excluir??","Alerta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE );
                 if(op==0){
                     FuncionarioServicos ws = ServicosFactory.getFuncionarioServicos();
                     ws.deletar(Long.parseLong(id));
                             
                 }
             
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Erro "+e.getMessage());
         }
     }
     private void filtrar(){
         try {
             if(jtPesq.getText().isEmpty()){
                 limpar();
                 preencherTabela();
             }else{
                 String query = "";
                 String filtro = jcomboPesq.getSelectedItem().toString();
                 if(filtro.equalsIgnoreCase("Código")){
                     query = "where idfuncionario like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("Nome")){
                     query = "where nome like '%"+jtPesq.getText()+"%'";
                 
                 }else if(filtro.equalsIgnoreCase("Telefone")){
                     query = "where telefone like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("cpf")){
                     query = "where cpf like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("cargo")){
                     query = "where cargo like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("sexo")){
                     query = "where sexo like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("salario")){
                     query = "where salario like '"+jtPesq.getText()+"%'";
                 }
                 FuncionarioServicos ps = ServicosFactory.getFuncionarioServicos();
                 ArrayList<Funcionario> fun = ps.filtrar(query);
                 
                 for(int i = 0; i< fun.size();i++){
                    dtm.addRow(new String[]{
                        String.valueOf(fun.get(i).getIdFuncionario()),
                        fun.get(i).getNome(),
                        fun.get(i).getTelefone(),
                        fun.get(i).getCpf(),
                        fun.get(i).getCargo(),
                        fun.get(i).getSexo(),                       
                        String.valueOf(fun.get(i).getSalario())
                    });
                }
                jTableFun.setModel(dtm);
             }
         } catch (Exception e) {
             jtPesq.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage());
         }
     }
     
     private void alterar(){
        
        int linha = jTableFun.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
            return;
        }
        
        
        
        jrCod.setText(jTableFun.getValueAt(linha, 0).toString());
        jtNome.setText(jTableFun.getValueAt(linha, 1).toString());
        jtSenha.setText(jTableFun.getValueAt(linha, 2).toString());
        jtTelefone.setText(jTableFun.getValueAt(linha, 3).toString());
        jtCPF.setText(jTableFun.getValueAt(linha, 4).toString());        
        if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("gerente")){
            jrGere.setSelected(true);
        }else  if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("recepcionista")){
            jrRecep.setSelected(true);
        }else if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("secretária")){
            jrSecre.setSelected(true);
        }else  if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("camareiro")){
            jrCam.setSelected(true);
        }else if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("supervisor")){
            jrSuper.setSelected(true);
        }else if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("controler")){
            jrCont.setSelected(true);
        }else  if(jTableFun.getValueAt(linha, 5).toString().equalsIgnoreCase("Cooder. de sistemas")){
            jrCoo.setSelected(true);
        }else{
            jrTel.setVisible(true);
        }   
        
        if(jTableFun.getValueAt(linha, 6).toString().equalsIgnoreCase("masculino")){
            jrMasculino.setSelected(true);
        } else {
            jrFeminino.setSelected(true);
        }
              
        jtSalario.setText(jTableFun.getValueAt(linha, 7).toString());        
        
        
         
        
               
    }//fecha alterar
     
     private void confirmarAlteracao(){
        try {
            Funcionario f = new Funcionario();
            
            if(!util.validacao.validarString(jtNome.getText())){

                throw new NumberFormatException("Nome invalido!");
            }
            
            if(jtSenha.getText().isEmpty()){
                throw new NumberFormatException("Senha invalida!");
            }
            if(!util.validacao.validarNumero(jtTelefone.getText())){
                throw new NumberFormatException("Telefone invalida!");
            }
            if(!util.validacao.validarCPF(jtCPF.getText())){
                throw new NumberFormatException("CPF invalido!");
            }
            if(!util.validacao.validarSalario(jtSalario.getText())){
                throw new NumberFormatException("Salário invalido!");
            }
            f.setIdFuncionario(Long.parseLong(jrCod.getText()));
            f.setNome(jtNome.getText());
            f.setSenha(jtSenha.getText());
            f.setTelefone(jtTelefone.getText());
            f.setCpf(jtCPF.getText());
            
            
            f.setSalario(Double.parseDouble(jtSalario.getText()));
            
            if(jrMasculino.isSelected()){
                f.setSexo(jrMasculino.getText());
            }else if(jrFeminino.isSelected()){
                f.setSexo(jrFeminino.getText());
            }else{
               
            }
            
            if(jrGere.isSelected()){
                f.setCargo(jrGere.getText());
            }else if(jrRecep.isSelected()){
                f.setCargo(jrRecep.getText());
            }else if(jrSecre.isSelected()){
                f.setCargo(jrSecre.getText());
            }else if(jrCam.isSelected()){
                f.setCargo(jrCam.getText());
            }else if(jrSuper.isSelected()){
                f.setCargo(jrSuper.getText());
            }else if(jrCont.isSelected()){
                f.setCargo(jrCont.getText());
            }else if(jrCoo.isSelected()){
                f.setCargo(jrCoo.getText());
            }else if(jrTel.isSelected()){
                f.setCargo(jrTel.getText());
            }else{
                throw new NumberFormatException("Selecione o Cargo!"); 
            }
            
            
            //Enviando o objeto pVO para o banco de dados
            FuncionarioServicos ps = ServicosFactory.getFuncionarioServicos();
            //Chamando o método 
            ps.alterarFuncionario(f);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Funcionario alterado com sucesso!");
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha confirmarAlteracao
    private void limparCampos(){
        jtNome.setText(null);
        jtSenha.setText(null);
        jrCod.setText(null);
        jtTelefone.setText(null);
        jtCPF.setText(null);
        jtSalario.setText(null);
        bgCargo.clearSelection();
        bgSexo.clearSelection();
        
    }
    
    
    private void buscarLinhaSelecionada(){
        try {
            /* Buscando a linha que o usuário clicou */
            int linha = jTableFun.getSelectedRow();
            
            /* Testando se o usuário selecionou alguma linha. */
            if (linha != -1) {
                
                /* todos os dados da linha selecionada pelo usuário */
                String idfuncionario = (String) jTableFun.getValueAt(linha, 0);
                String nome = (String) jTableFun.getValueAt(linha, 1);
                String senha = (String) jTableFun.getValueAt(linha, 2);
                String telefone = (String) jTableFun.getValueAt(linha, 3);
                String cpf = (String) jTableFun.getValueAt(linha, 4);
                
                String cargo = (String) jTableFun.getValueAt(linha, 5);
                String sexo = (String) jTableFun.getValueAt(linha, 6);
                String salario = (String) jTableFun.getValueAt(linha, 7);
               
               
               
                
                JOptionPane.showMessageDialog(this,
                        "Dados do Funcionario selecionado: "
                        +"\ncódigo: "+idfuncionario
                        +"\nNome: "+nome
                        +"\nSenha: "+senha
                        +"\nTelefone: "+telefone
                        +"\nCPF: "+cpf
                        +"\nCargo: "+cargo
                        +"\nSexo: "+sexo
                        +"\nSalário: "+salario
                        
                );
            } else {
                JOptionPane.showMessageDialog(this,
                        "Você não selecionou nenhuma linha!");
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao selecionar uma linha! " + e.getMessage());
        }//fecha catch
    }//fecha método
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscarLinhaSelecionada();// TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
        limpar();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
       limpar();
       preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jcomboPesqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboPesqItemStateChanged
        limpar();
        filtrar();
        
    }//GEN-LAST:event_jcomboPesqItemStateChanged

    private void jTableFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFunMouseClicked
        alterar();
    }//GEN-LAST:event_jTableFunMouseClicked

    private void jtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCPFFocusGained
        if(jtCPF.getText().isEmpty()){
            jtCPF.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
            jtCPF.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        }
    }//GEN-LAST:event_jtCPFFocusGained

    private void jtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCPFKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtTelefone.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtCPFKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if(jtNome.getText().isEmpty()){
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
            jtNome.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSenha.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSalarioFocusLost
        if(jtSalario.getText().isEmpty()){
            jtSalario.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
            jtSalario.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        }
    }//GEN-LAST:event_jtSalarioFocusLost

    private void jtSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSalarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrGere.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtSalarioKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrFeminino.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
            limparCampos();
            preencherTabela();
        }//fecha if
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jrRecepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrRecepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCam.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrRecepKeyPressed

    private void jrGereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrGereKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSecre.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrGereKeyPressed

    private void jrSuperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSuperKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCoo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSuperKeyPressed

    private void jrCamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCamKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCont.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCamKeyPressed

    private void jrSecreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSecreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrSuper.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSecreKeyPressed

    private void jrContKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrContKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrTel.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrContKeyPressed

    private void jrCooKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCooKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrRecep.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCooKeyPressed

    private void jrTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrTelKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrMasculino.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrTelKeyPressed

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        if(jtTelefone.getText().isEmpty()){
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSalario.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jrCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrCodFocusLost
        if(jrCod.getText().isEmpty()){
            jrCod.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
            jrCod.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        }
    }//GEN-LAST:event_jrCodFocusLost

    private void jrCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCodKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtNome.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCodKeyPressed

    private void jtPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboPesq.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtPesqKeyPressed

    private void jcomboPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboPesqKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbAtualizar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jcomboPesqKeyPressed

    private void jbAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAtualizarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbLimpar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbAtualizarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbBuscar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbBuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbDeletar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbBuscarKeyPressed

    private void jbDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDeletarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrCod.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbDeletarKeyPressed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
            preencherTabela();
            limparCampos();
        }//fecha if
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        confirmarAlteracao();
        limpar();
        preencherTabela();
        alterar();
        preencherTabela();
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSenhaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCPF.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtSenhaKeyPressed

    private void jtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSenhaFocusLost
        if(jtSenha.getText().isEmpty()){            
            jtSenha.setBorder(BorderFactory.createLineBorder(Color.red));

        }else{
           jtSenha.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            
        }
    }//GEN-LAST:event_jtSenhaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCargo;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JTable jTableFun;
    private javax.swing.JScrollPane jTableFunc;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcomboPesq;
    private javax.swing.JRadioButton jrCam;
    private javax.swing.JTextField jrCod;
    private javax.swing.JRadioButton jrCont;
    private javax.swing.JRadioButton jrCoo;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrGere;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JRadioButton jrRecep;
    private javax.swing.JRadioButton jrSecre;
    private javax.swing.JRadioButton jrSuper;
    private javax.swing.JRadioButton jrTel;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtSalario;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}