/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Funcionario;
import modelo.Quarto;
import modelo.Reserva;
import servicos.FuncionarioServicos;
import servicos.QuartoServicos;
import servicos.ReservaServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Vinicius
 */
public class UIManRes extends javax.swing.JInternalFrame {
     DefaultTableModel dtm = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"Código","Data Entrada","Data Saída","Código Quarto","Código Funcionario","Código Hospede"});
    /**
     * Creates new form UIManRes
     */
    public UIManRes() {
        initComponents();
        preencherTabela();
        preencherComboQuarto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jtPesq = new javax.swing.JTextField();
        jcomboPesq = new javax.swing.JComboBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTableFunc = new javax.swing.JScrollPane();
        jTableFun = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jbBUscar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtDataEntrada = new javax.swing.JTextField();
        jtDataSaida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboQuarto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Pesquisa");

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboPesq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "Telefone", "CPF", "Cargo", "Sexo", "Salário" }));
        jcomboPesq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboPesqItemStateChanged(evt);
            }
        });
        jcomboPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboPesqKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcomboPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jcomboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcomboPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableFun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data Entrada", "Data Saída", "Código Quarto", "Código Funcionario", "Código Hospede"
            }
        ));
        jTableFun.getTableHeader().setReorderingAllowed(false);
        jTableFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFunMouseClicked(evt);
            }
        });
        jTableFunc.setViewportView(jTableFun);

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });
        jbAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAtualizarKeyPressed(evt);
            }
        });

        jbBUscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/detalhes.png"))); // NOI18N
        jbBUscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBUscarActionPerformed(evt);
            }
        });
        jbBUscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbBUscarKeyPressed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });
        jbDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDeletarKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jTableFunc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbBUscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTableFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbBUscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBUscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletar))
                    .addComponent(jTableFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Data de Entrada:");

        jLabel10.setText("Data de Saída:");

        jtDataEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDataEntradaFocusLost(evt);
            }
        });
        jtDataEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDataEntradaKeyPressed(evt);
            }
        });

        jtDataSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDataSaidaFocusLost(evt);
            }
        });
        jtDataSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDataSaidaKeyPressed(evt);
            }
        });

        jLabel12.setText("Quarto:");

        jComboQuarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboQuartoKeyPressed(evt);
            }
        });

        jLabel3.setText("Código");

        jtCod.setEditable(false);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtDataEntrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtDataSaida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jComboQuarto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtCod, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDataEntrada)
                            .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtDataSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jComboQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtCod, jtDataEntrada, jtDataSaida});

        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jComboQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLayeredPane4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtCod, jtDataEntrada, jtDataSaida});

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherTabela(){
        try {
             ReservaServicos FS = ServicosFactory.getReservaServicos();
             ArrayList<Reserva> func = FS.buscarReserva();
             
             for(int i=0; i<func.size(); i++){
                dtm.addRow(new String[]{
                    String.valueOf(func.get(i).getIdReserva()),
                    func.get(i).getDataEntrada(),
                    func.get(i).getDataSaida(),
                    String.valueOf(func.get(i).getQuarto().getIdQuarto()),
                    String.valueOf(func.get(i).getFuncinario().getIdFuncionario()),
                    String.valueOf(func.get(i).getHospede().getIdHospede())
                });
                
             }//fecha for
             jTableFun.setModel(dtm);
         } catch (Exception e) {
             
              e.printStackTrace();
             JOptionPane.showMessageDialog(rootPane,"Erro!"+e.getMessage());
         }//fecha catch
     }//fecha preenchertabela
    
    
     private void limpar(){
         dtm.setNumRows(0);
     }//fecha limpar
     
     Reserva r = new Reserva();
     private void deletar(){
         try {
             int linha = jTableFun.getSelectedRow();
             if(linha ==-1){
                 JOptionPane.showMessageDialog(rootPane, "Selecione uma linha ");
             }else{
                 String id = jTableFun.getValueAt(linha, 0).toString();
                 String idQu = jTableFun.getValueAt(linha, 3).toString();
                 String idhos = jTableFun.getValueAt(linha, 5).toString();
                 int op = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja excluir??","Alerta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE );
                 if(op==0){
                     ReservaServicos ws = ServicosFactory.getReservaServicos();
                     ws.deletar(Long.parseLong(id),Long.parseLong(idQu),Long.parseLong(idhos));
                             
                 }
             
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Erro "+e.getMessage());
         }
     }
     private void filtrar(){
         try {
             if(jtPesq.getText().isEmpty()){
                 limpar();
                 preencherTabela();
             }else{
                 String query = "";
                 String filtro = jcomboPesq.getSelectedItem().toString();
                 if(filtro.equalsIgnoreCase("Código")){
                     query = "where idreserva like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("Data Entrada")){
                     query = "where dataentrada like '%"+jtPesq.getText()+"%'";
                 
                 }else if(filtro.equalsIgnoreCase("Data Saída")){
                     query = "where datasaida like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("idquarto")){
                     query = "where idquarto like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("idfuncionario")){
                     query = "where idfuncionario like '"+jtPesq.getText()+"%'";
                 }else if(filtro.equalsIgnoreCase("idhospede")){
                     query = "where idhospede like '"+jtPesq.getText()+"%'";
                 }
                 ReservaServicos ps = ServicosFactory.getReservaServicos();
                 ArrayList<Reserva> func = ps.filtrar(query);
                 
                 for(int i = 0; i< func.size();i++){
                    dtm.addRow(new String[]{
                        String.valueOf(func.get(i).getIdReserva()),
                        func.get(i).getDataEntrada(),
                        func.get(i).getDataSaida(),
                        String.valueOf(func.get(i).getFuncinario().getIdFuncionario()),
                        String.valueOf(func.get(i).getQuarto().getIdQuarto()),
                        String.valueOf(func.get(i).getHospede().getIdHospede())
                    });
                }
                jTableFun.setModel(dtm);
             }
         } catch (Exception e) {
             jtPesq.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage());
         }
     }
     
     private void alterar(){
        
        int linha = jTableFun.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
            return;
        }
        jtCod.setText(jTableFun.getValueAt(linha, 0).toString());
        jtDataEntrada.setText(jTableFun.getValueAt(linha, 1).toString());
        jtDataSaida.setText(jTableFun.getValueAt(linha, 2).toString());
          
    }//fecha alterar
 
    Funcionario f = new Funcionario();
    
    
    private void preencherComboQuarto(){
        try {
            
            
            QuartoServicos ss = ServicosFactory.getQuartoServicos();
             ArrayList<Quarto> s = ss.buscarQuarto();
            
           
                for (int i = 0; i < s.size(); i++) {
                    if(s.get(i).getStatus().equalsIgnoreCase("vago")){
                        jComboQuarto.addItem(s.get(i));
                    }
                    
                }
            

            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha método preencherCombo
     
     private void confirmarAlteracao(){
        try {
            if(!util.validacao.validarData(jtDataEntrada.getText())){
                throw new NumberFormatException("Data de entrada invalido!");
            }
            if(!util.validacao.validarData(jtDataSaida.getText())){
                throw new NumberFormatException("Data de saida invalido!");
            }
            r.setIdReserva(Long.parseLong(jtCod.getText()));
            r.setDataEntrada(jtDataEntrada.getText());
            r.setDataSaida(jtDataSaida.getText());
            
            
            
            r.setQuarto((Quarto)jComboQuarto.getSelectedItem());
            
            
            
            //Enviando o objeto pVO para o banco de dados
            ReservaServicos ps = ServicosFactory.getReservaServicos();
            //Chamando o método 
            ps.alterarQuarto(r);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Reserva alterado com sucesso!");
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha confirmarAlteracao
    private void limparCampos(){
        jtDataEntrada.setText(null);
        jtDataSaida.setText(null);
        jtCod.setText(null);
        
        jComboQuarto.removeAllItems();
    }
    
    
    private void buscarLinhaSelecionada(){
        try {
            /* Buscando a linha que o usuário clicou */
            int linha = jTableFun.getSelectedRow();
            
            /* Testando se o usuário selecionou alguma linha. */
            if (linha != -1) {
                
                /* todos os dados da linha selecionada pelo usuário */
                String idReserva = (String) jTableFun.getValueAt(linha, 0);
                String dataEntrada = (String) jTableFun.getValueAt(linha, 1);
                String dataSaida = (String) jTableFun.getValueAt(linha, 2);
                String idquarto = (String) jTableFun.getValueAt(linha, 3);
                String idFuncionario = (String) jTableFun.getValueAt(linha, 4);
                
                String idHospede = (String) jTableFun.getValueAt(linha, 5);
                         
                JOptionPane.showMessageDialog(this,
                        "Dados da Reserva selecionado: "
                        +"\ncódigo: "+idReserva
                        +"\nData de Entrada: "+dataEntrada
                        +"\nData de Saída: "+dataSaida
                        +"\nCódgigo Quarto: "+idquarto
                        +"\nCódigo Funcionario: "+idFuncionario
                        +"\nCódigo Hospede: "+idHospede
                        +"\nTotal: "+r.calcularTotal()
                        
                        
                );
            } else {
                JOptionPane.showMessageDialog(this,
                        "Você não selecionou nenhuma linha!");
            }//fecha else
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao selecionar uma linha! " + e.getMessage());
        }//fecha catch
    }//fecha método
    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jcomboPesqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboPesqItemStateChanged
        limpar();
        filtrar();

    }//GEN-LAST:event_jcomboPesqItemStateChanged

    private void jTableFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFunMouseClicked
        alterar();
    }//GEN-LAST:event_jTableFunMouseClicked

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterar();
        
        limpar();
        preencherTabela();
        preencherComboQuarto();
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limpar();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAtualizarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbBUscar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbAtualizarKeyPressed

    private void jbBUscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBUscarActionPerformed
        buscarLinhaSelecionada();
    }//GEN-LAST:event_jbBUscarActionPerformed

    private void jbBUscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbBUscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbLimpar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbBUscarKeyPressed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbDeletar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
        limpar();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDeletarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtDataEntrada.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jbDeletarKeyPressed

    private void jtPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboPesq.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtPesqKeyPressed

    private void jcomboPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboPesqKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbAtualizar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jcomboPesqKeyPressed

    private void jtDataEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDataEntradaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtDataSaida.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtDataEntradaKeyPressed

    private void jtDataSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDataSaidaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jComboQuarto.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtDataSaidaKeyPressed

    private void jComboQuartoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboQuartoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
            limparCampos();
            limpar();
            preencherTabela();
            preencherComboQuarto();
        }//fecha if
    }//GEN-LAST:event_jComboQuartoKeyPressed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
            limparCampos();
            limpar();
            preencherTabela();
            preencherComboQuarto();
        }//fecha if
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jtDataEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataEntradaFocusLost
        if(jtDataEntrada.getText().isEmpty()){            
            jtDataEntrada.setBorder(BorderFactory.createLineBorder(Color.RED));
        }else{
           jtDataEntrada.setBorder(BorderFactory.createLineBorder(Color.gray));    
        }
    }//GEN-LAST:event_jtDataEntradaFocusLost

    private void jtDataSaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataSaidaFocusLost
        if(jtDataSaida.getText().isEmpty()){            
            jtDataSaida.setBorder(BorderFactory.createLineBorder(Color.RED));
        }else{
           jtDataSaida.setBorder(BorderFactory.createLineBorder(Color.gray));    
        }
    }//GEN-LAST:event_jtDataSaidaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JTable jTableFun;
    private javax.swing.JScrollPane jTableFunc;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbBUscar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox jcomboPesq;
    private javax.swing.JTextField jtCod;
    private javax.swing.JTextField jtDataEntrada;
    private javax.swing.JTextField jtDataSaida;
    private javax.swing.JTextField jtPesq;
    // End of variables declaration//GEN-END:variables
}
